"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { fetchHistory, deleteHistoryItem, getDownloadUrl, type HistoryItem } from "@/lib/api";

function formatDate(iso: string) {
  try {
    return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit" });
  } catch { return iso; }
}

function ScoreBadge({ score }: { score: number }) {
  const cls = score >= 80 ? "text-green-400 bg-green-500/10 border-green-500/20"
            : score >= 60 ? "text-yellow-400 bg-yellow-500/10 border-yellow-500/20"
            : "text-red-400 bg-red-500/10 border-red-500/20";
  return (
    <span className={`text-xs font-bold border rounded-full px-2.5 py-0.5 ${cls}`}>
      {Math.round(score)}
    </span>
  );
}

function FormatBadge({ fmt }: { fmt: string }) {
  return (
    <span className="text-xs bg-brand-500/10 border border-brand-500/20 text-brand-400 rounded-full px-2.5 py-0.5 capitalize">
      {fmt}
    </span>
  );
}

export default function HistoryPage() {
  const router = useRouter();
  const [items, setItems] = useState<HistoryItem[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [deleting, setDeleting] = useState<string>("");

  useEffect(() => {
    fetchHistory()
      .then(res => setItems(res.items))
      .catch(e => setError(e.message))
      .finally(() => setLoading(false));
  }, []);

  async function handleDelete(id: string) {
    setDeleting(id);
    await deleteHistoryItem(id);
    setItems(prev => prev.filter(i => i.id !== id));
    setDeleting("");
  }

  return (
    <div className="min-h-screen bg-surface">
      {/* Nav */}
      <nav className="border-b border-border px-6 py-4 flex items-center justify-between max-w-5xl mx-auto">
        <Link href="/" className="flex items-center gap-2">
          <span className="text-lg font-bold text-white tracking-tight">TopNotch</span>
          <span className="text-lg font-bold text-brand-500">Resume</span>
        </Link>
        <Link href="/generate" className="btn-primary text-sm">
          + New Resume
        </Link>
      </nav>

      <main className="max-w-5xl mx-auto px-6 py-10">
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-white">Generation History</h1>
          <p className="text-sm text-slate-500 mt-1">All resumes generated by JARVIS on this device.</p>
        </div>

        {loading && (
          <div className="text-center py-16 text-slate-500">Loading history…</div>
        )}

        {error && (
          <div className="card p-6 text-center text-red-400 text-sm">
            Failed to load history: {error}
          </div>
        )}

        {!loading && !error && items.length === 0 && (
          <div className="card p-12 text-center space-y-4">
            <div className="text-4xl">📋</div>
            <p className="text-white font-medium">No resumes generated yet</p>
            <p className="text-sm text-slate-500">Generate your first resume to see it here.</p>
            <Link href="/generate" className="btn-primary text-sm inline-block mt-2">
              Build My Resume
            </Link>
          </div>
        )}

        {items.length > 0 && (
          <div className="space-y-3">
            {/* Table header */}
            <div className="hidden md:grid grid-cols-[1fr_1fr_auto_auto_auto_auto] gap-4 px-4 py-2 text-xs text-slate-600 uppercase tracking-wide font-medium">
              <span>Candidate</span>
              <span>Role / Company</span>
              <span>Format</span>
              <span>ATS</span>
              <span>Time</span>
              <span>Actions</span>
            </div>

            {items.map(item => (
              <div
                key={item.id}
                className="card p-4 grid grid-cols-1 md:grid-cols-[1fr_1fr_auto_auto_auto_auto] gap-3 md:gap-4 items-center hover:border-brand-500/30 transition-colors"
              >
                <div>
                  <button
                    onClick={() => router.push(`/generate?restore=${item.id}`)}
                    className="text-sm font-medium text-white hover:text-brand-400 transition-colors text-left"
                    title="Click to restore all sections and re-generate"
                  >
                    {item.candidate || "Unknown"}
                  </button>
                  <p className="text-xs text-slate-600 mt-0.5">{formatDate(item.created_at)}</p>
                </div>
                <div>
                  <p className="text-sm text-slate-300">{item.role || "—"}</p>
                  {item.company && <p className="text-xs text-slate-600 mt-0.5">{item.company}</p>}
                </div>
                <FormatBadge fmt={item.format || "ats"} />
                <ScoreBadge score={item.ats_score} />
                <p className="text-xs text-slate-600">{(item.gen_ms / 1000).toFixed(1)}s</p>
                <div className="flex items-center gap-2 flex-wrap">
                  <a
                    href={getDownloadUrl(item.id)}
                    download
                    className="text-xs text-brand-400 hover:text-brand-300 transition-colors"
                  >
                    ↓ .docx
                  </a>
                  <button
                    onClick={() => router.push(`/generate?restore=${item.id}`)}
                    className="text-xs text-emerald-400 hover:text-emerald-300 transition-colors"
                    title="Restore all 7 sections and re-generate"
                  >
                    ↺ Restore
                  </button>
                  {item.session_id && (
                    <button
                      onClick={() => router.push(`/enhance?id=${item.session_id}`)}
                      className="text-xs text-brand-400 hover:text-brand-300 transition-colors"
                      title="Enhance with RSEA"
                    >
                      ✨ Enhance
                    </button>
                  )}
                  <button
                    onClick={() => handleDelete(item.id)}
                    disabled={deleting === item.id}
                    className="text-xs text-slate-600 hover:text-red-400 transition-colors disabled:opacity-40"
                  >
                    {deleting === item.id ? "…" : "Delete"}
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}

        {items.length > 0 && (
          <p className="text-center text-xs text-slate-700 mt-8">
            {items.length} resume{items.length !== 1 ? "s" : ""} · Downloads expire 24 hours after generation
          </p>
        )}
      </main>
    </div>
  );
}
